# Generated by Django 3.0.4 on 2021-04-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
