# Generated by Django 3.0.4 on 2021-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0010_remove_choice_sphere'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sphere',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
