# Generated by Django 3.0.4 on 2021-04-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0011_question_sphere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
