# Generated by Django 3.0.4 on 2021-04-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0012_auto_20210418_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere', models.CharField(blank=True, max_length=50)),
                ('question_text', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
