# Generated by Django 3.0.4 on 2021-04-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0013_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
