# Generated by Django 3.0.4 on 2021-04-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0015_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
