# Generated by Django 3.0.4 on 2021-04-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0018_auto_20210418_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
