# Generated by Django 3.0.4 on 2021-04-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0021_choice_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
