# Generated by Django 3.0.4 on 2021-04-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkresult',
            name='homework_file',
            field=models.CharField(max_length=1),
        ),
    ]
