# Generated by Django 3.0.4 on 2021-04-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20210420_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkresult',
            name='homework_task',
        ),
        migrations.RemoveField(
            model_name='homeworkresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='HomeworkResult',
        ),
    ]
