# Generated by Django 3.0.4 on 2021-04-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_homework_homeworkresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkresult',
            name='homework_task',
        ),
        migrations.RemoveField(
            model_name='homeworkresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='HomeworkResult',
        ),
    ]
