# Generated by Django 3.0.4 on 2021-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='task.Answer'),
        ),
    ]
