# Generated by Django 3.0.4 on 2021-04-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210420_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='question', to='task.Answer'),
        ),
    ]
