# Generated by Django 3.0.4 on 2021-04-20 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_auto_20210420_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('rated', 'Rated'), ('not_rated', 'Not Rated'), ('done', 'Done'), ('in_progress', 'In progress'), ('planned', 'Planned'), ('fail', 'Fail')], max_length=20)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Answer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.TestTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
