# Generated by Django 3.0.4 on 2021-04-20 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0005_auto_20210420_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answers', models.ManyToManyField(related_name='question', to='task.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('sphere', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('question', models.ManyToManyField(to='task.Question')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('rated', 'Rated'), ('not_rated', 'Not Rated'), ('done', 'Done'), ('in_progress', 'In progress'), ('planned', 'Planned'), ('fail', 'Fail')], max_length=20)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Answer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.TestTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
