# Generated by Django 3.0.4 on 2021-04-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_answer_personalresult_question_testtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalresult',
            name='bb',
            field=models.IntegerField(default=0),
        ),
    ]
