# Generated by Django 3.0.4 on 2021-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_personalresult_bb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalresult',
            name='bb',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
