# Generated by Django 3.0.4 on 2021-04-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20210420_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalresult',
            name='bb',
        ),
    ]
